site_name: EMT Vessels
nav:
    - Home: index.md
    - Skills Matrix: skills_matrix.md
    - Aide Memoire: first_aid/am/aide_memoire.md
    - Mental Health: first_aid/mhfa/mental_health.md
    - PHECC: first_aid/phecc.md
    - About: about.md
theme:
  name: 'material'
repo_url: https://github.com/markmcsherry/EMT-Vessels
edit_uri: blob/main/docs/
docs_dir: docs